language: go
os:
  - linux
go:
  - 1.11
sudo: required
services:
  - docker
install:
  - go mod download
  - mkdir -p $GOPATH/src/github.com/operator-framework/
  - git clone https://github.com/operator-framework/operator-sdk $GOPATH/src/github.com/operator-framework/operator-sdk
  - cd $GOPATH/src/github.com/operator-framework/operator-sdk
  - make dep
  - make install
  - cd /home/travis/gopath/src/github.com/pickledrick/vpc-peering-operator
script:
  - make
