language: go
os:
  - linux
go:
  - 1.11
sudo: required
services:
  - docker
env:
  - DEP_VERSION="0.4.1"
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64
    -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
install:
  - dep ensure
  - mkdir -p $GOPATH/src/github.com/operator-framework/
  - git clone https://github.com/operator-framework/operator-sdk $GOPATH/src/github.com/operator-framework/operator-sdk
  - cd $GOPATH/src/github.com/operator-framework/operator-sdk
  - make dep
  - make install
  - cd /home/travis/gopath/src/github.com/pickledrick/vpc-peering-operator
script:
  - make
