apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vpcpeerings.r4.vc
spec:
  group: r4.vc
  names:
    kind: VpcPeering
    listKind: VpcPeeringList
    plural: vpcpeerings
    singular: vpcpeering
  scope: Namespaced
  version: v1
